/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 beach.glb --transform 
Files: beach.glb [5.54MB] > /Users/dhruvyadav/3dGame/public/models/beach-transformed.glb [299.17KB] (95%)
Author: Batuhan13 (https://sketchfab.com/Batuhan13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.
com/3d-models/beach-race-game-prototype-map-6ca71306801744c48cdb66f6d573258b
Title: Beach Race Game Prototype Map
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Beach(props) {
  const { nodes, materials } = useGLTF('/models/beach-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0,10,0]} scale={[1000,1000,1000]}>
      <mesh geometry={nodes.BeachProp_ColorPalette_0.geometry} material={materials.ColorPalette} position={[-25534.604, 94.011, -26733.008]} rotation={[Math.PI / 2, 0, 0]} scale={1.4} />
      <mesh geometry={nodes.Plane069_ColorPaletteWater_0.geometry} material={materials.ColorPaletteWater} position={[-28214.338, -318.198, -20745.439]} />
      <instancedMesh args={[nodes.Mball007_ColorPalette_0.geometry, materials.ColorPalette, 6]} instanceMatrix={nodes.Mball007_ColorPalette_0.instanceMatrix} />
      <instancedMesh args={[nodes.Icosphere069_ColorPalette_0.geometry, materials.ColorPalette, 7]} instanceMatrix={nodes.Icosphere069_ColorPalette_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/beach-transformed.glb')
