/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 phoenix_bird.glb --transform 
Files: phoenix_bird.glb [1.63MB] > /Users/dhruvyadav/3dGame/public/models/phoenix_bird-transformed.glb [462.76KB] (72%)
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export function Bird(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/phoenix_bird-transformed.glb')
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // console.log(actions);
    // actions['Take 001'].play();
  },
  [actions])
  useFrame((state, delta) => {
    // Calculate the position on the circle
    const radius = 20;
    const angle = state.clock.getElapsedTime() * 0.5; // Slow down the speed by multiplying with a factor
    group.current.position.x = radius * Math.cos(angle);
    group.current.position.z = radius * Math.sin(angle);
    group.current.rotation.y = angle;
});

  return (
    <group ref={group} {...props} dispose={null}  >
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.MatI_Ride_FengHuang_01a} skeleton={nodes.Object_7.skeleton} position={[-0.625, 0, -17.137]} rotation={[0, 0.053, 0]} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.MatI_Ride_FengHuang_01b} skeleton={nodes.Object_8.skeleton} position={[-0.625, 0, -17.137]} rotation={[0, 0.053, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/phoenix_bird-transformed.glb')
