/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 low_poly_humanoid_robot.glb 
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-humanoid-robot-bad584b9fbe04c85bc57438842969270
Title: Low Poly Humanoid Robot
*/

import React, { useContext, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { RefContext } from '../../context/context'

export function Character(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/low_poly_humanoid_robot.glb')
  const { actions } = useAnimations(animations, group)
  const {isWalking} = useContext(RefContext);

 console.log(actions);


 useEffect(() => {
  // if isWalking is true then play else stop 
  if(isWalking.current){
    actions["walk"].play()
  }
  else{
    actions["walk"].stop()
  }
}
, [isWalking.current])


  return (
    <group ref={group} {...props} dispose={null} scale={[1,1,1]} rotation={[0,Math.PI,0]} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="LowPolyRobotfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="robot_lp" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.lpRobot} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_humanoid_robot.glb')
