/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hut.glb --transform 
Files: hut.glb [1.39MB] > /Users/dhruvyadav/3dGame/public/models/hut-transformed.glb [143.66KB] (90%)
Author: Fishboe (https://sketchfab.com/ministephen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-be18892d167f40d9bb4d7dcae0eb0573
Title: House
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hut(props) {
  const { nodes, materials } = useGLTF('/models/hut-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.door1} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.door2} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.panesl} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.slats} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.woodfloor} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.foof} rotation={[-Math.PI / 2, 0, 0]} scale={0.425} />
    </group>
  )
}

useGLTF.preload('/hut-transformed.glb')
