/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 low_poly_city-pack.glb --transform 
Files: low_poly_city-pack.glb [42MB] > /Users/dhruvyadav/3dGame/public/models/low_poly_city-pack-transformed.glb [1.05MB] (97%)
Author: medmgames (https://sketchfab.com/medmgames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-city-pack-c693dae1fe06403ea1e0bcf4e9db108a
Title: Low Poly City-Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from "@react-three/rapier"


export function Industry(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_city-pack-transformed.glb')

  return (
    <RigidBody type="fixed" colliders="trimesh"  >
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Straight_Road_Material007_0.geometry} material={materials['Material.060']} position={[-198, 0, 306]} />
        <instancedMesh args={[nodes.Road_Material001_0.geometry, materials['Material.060'], 108]} instanceMatrix={nodes.Road_Material001_0.instanceMatrix} />
        <instancedMesh args={[nodes.Walking_Road_Material002_0.geometry, materials['Material.060'], 13]} instanceMatrix={nodes.Walking_Road_Material002_0.instanceMatrix} />
        <instancedMesh args={[nodes.Road025_Material001_0.geometry, materials['Material.060'], 85]} instanceMatrix={nodes.Road025_Material001_0.instanceMatrix} />
        <instancedMesh args={[nodes.Straight_Road001_Material007_0.geometry, materials['Material.060'], 42]} instanceMatrix={nodes.Straight_Road001_Material007_0.instanceMatrix} />
        <instancedMesh args={[nodes.Walking_Road2_Material008_0.geometry, materials['Material.060'], 5]} instanceMatrix={nodes.Walking_Road2_Material008_0.instanceMatrix} />
        <instancedMesh args={[nodes.Straight_Road033_Material007_0.geometry, materials['Material.060'], 26]} instanceMatrix={nodes.Straight_Road033_Material007_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground_Material009_0.geometry, materials['Material.060'], 174]} instanceMatrix={nodes.Ground_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground096_Material009_0.geometry, materials['Material.060'], 23]} instanceMatrix={nodes.Ground096_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground191_Material009_0.geometry, materials['Material.060'], 54]} instanceMatrix={nodes.Ground191_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground242_Material009_0.geometry, materials['Material.060'], 64]} instanceMatrix={nodes.Ground242_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground267_Material009_0.geometry, materials['Material.060'], 15]} instanceMatrix={nodes.Ground267_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.OPEN_ROAD001_Material014_0.geometry, materials['Material.060'], 5]} instanceMatrix={nodes.OPEN_ROAD001_Material014_0.instanceMatrix} />
        <instancedMesh args={[nodes.Walking_Road2010_Material023_0.geometry, materials['Material.060'], 6]} instanceMatrix={nodes.Walking_Road2010_Material023_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground024_Material009_0.geometry, materials['Material.060'], 13]} instanceMatrix={nodes.Ground024_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground025_Material009_0.geometry, materials['Material.060'], 13]} instanceMatrix={nodes.Ground025_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground334_Material009_0.geometry, materials['Material.060'], 15]} instanceMatrix={nodes.Ground334_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ground374_Material009_0.geometry, materials['Material.060'], 13]} instanceMatrix={nodes.Ground374_Material009_0.instanceMatrix} />
        <instancedMesh args={[nodes.TRIANGLE_TREE_Material031_0.geometry, materials['Material.060'], 23]} instanceMatrix={nodes.TRIANGLE_TREE_Material031_0.instanceMatrix} />
        <instancedMesh args={[nodes.SPHEREICAL_TREE1_Material032_0.geometry, materials['Material.060'], 21]} instanceMatrix={nodes.SPHEREICAL_TREE1_Material032_0.instanceMatrix} />
        <instancedMesh args={[nodes.REAL_TREE_Material033_0.geometry, materials['Material.060'], 27]} instanceMatrix={nodes.REAL_TREE_Material033_0.instanceMatrix} />
        <instancedMesh args={[nodes.TREE_Material037_0.geometry, materials['Material.060'], 30]} instanceMatrix={nodes.TREE_Material037_0.instanceMatrix} />
        <instancedMesh args={[nodes.ROCK_Material039_0.geometry, materials['Material.060'], 6]} instanceMatrix={nodes.ROCK_Material039_0.instanceMatrix} />
        <instancedMesh args={[nodes.TREE_POT_Material041_0.geometry, materials['Material.060'], 47]} instanceMatrix={nodes.TREE_POT_Material041_0.instanceMatrix} />
        <instancedMesh args={[nodes.SQUARE_TREE_Material042_0.geometry, materials['Material.060'], 14]} instanceMatrix={nodes.SQUARE_TREE_Material042_0.instanceMatrix} />
        <instancedMesh args={[nodes.TABLE_Material046_0.geometry, materials['Material.060'], 5]} instanceMatrix={nodes.TABLE_Material046_0.instanceMatrix} />
        <instancedMesh args={[nodes.CHAIR_Material047_0.geometry, materials['Material.060'], 5]} instanceMatrix={nodes.CHAIR_Material047_0.instanceMatrix} />
        <instancedMesh args={[nodes.CHAIR001_Material047_0.geometry, materials['Material.060'], 10]} instanceMatrix={nodes.CHAIR001_Material047_0.instanceMatrix} />
        <instancedMesh args={[nodes.SQUARE_TABLE_Material049_0.geometry, materials['Material.060'], 5]} instanceMatrix={nodes.SQUARE_TABLE_Material049_0.instanceMatrix} />
        <instancedMesh args={[nodes.CHAIR011_Material047_0.geometry, materials['Material.060'], 5]} instanceMatrix={nodes.CHAIR011_Material047_0.instanceMatrix} />
        <instancedMesh args={[nodes.TALL_CHAIR002_Material051_0.geometry, materials['Material.060'], 21]} instanceMatrix={nodes.TALL_CHAIR002_Material051_0.instanceMatrix} />
        <instancedMesh args={[nodes.TRAFFIC_LIGHT004_Material003_0.geometry, materials['Material.060'], 12]} instanceMatrix={nodes.TRAFFIC_LIGHT004_Material003_0.instanceMatrix} />
        <instancedMesh args={[nodes.TRAFFIC_LIGHT005_Material003_0.geometry, materials['Material.060'], 10]} instanceMatrix={nodes.TRAFFIC_LIGHT005_Material003_0.instanceMatrix} />
        <instancedMesh args={[nodes.LIGHT_STREET_Material048_0.geometry, materials['Material.060'], 48]} instanceMatrix={nodes.LIGHT_STREET_Material048_0.instanceMatrix} />
        <instancedMesh args={[nodes.TRAFFIC_CONE_Material036_0.geometry, materials['Material.060'], 9]} instanceMatrix={nodes.TRAFFIC_CONE_Material036_0.instanceMatrix} />
        <instancedMesh args={[nodes.TRAFFIC_CYLINDER_Material044_0.geometry, materials['Material.060'], 10]} instanceMatrix={nodes.TRAFFIC_CYLINDER_Material044_0.instanceMatrix} />
        <instancedMesh args={[nodes.LIGHT_STREET2_Material055_0.geometry, materials['Material.060'], 6]} instanceMatrix={nodes.LIGHT_STREET2_Material055_0.instanceMatrix} />
        <instancedMesh args={[nodes.LIGHT_STREET2003_Material055_0.geometry, materials['Material.060'], 7]} instanceMatrix={nodes.LIGHT_STREET2003_Material055_0.instanceMatrix} />
        <instancedMesh args={[nodes.GREEN_RECYCLE_BIN010_Material058_0.geometry, materials['Material.060'], 6]} instanceMatrix={nodes.GREEN_RECYCLE_BIN010_Material058_0.instanceMatrix} />
      </group>
    </RigidBody>

  )
}

useGLTF.preload('/low_poly_city-pack-transformed.glb')
