/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 japaneseBus.glb --transform 
Files: japaneseBus.glb [1.16MB] > /Users/dhruvyadav/3dGame/public/models/japaneseBus-transformed.glb [64.9KB] (94%)
Author: VRC-IW (https://sketchfab.com/VRC-IW)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/japanese-bus-nagoya-city-bus-aichi-37c0a04a7aef4139b6aa037d17e768e5
Title: Japanese bus "Nagoya City Bus" (Aichi)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from "@react-three/rapier"

export function JapaneseBus(props) {
  const { nodes, materials } = useGLTF('/models/japaneseBus-transformed.glb')
  return (

    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh" >
        <mesh geometry={nodes.Cube004_Nagoya_0.geometry} material={materials.Nagoya} position={[15.803, 1.715, -40.714]} rotation={[-Math.PI / 2, 0, 0]} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/japaneseBus-transformed.glb')
