/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 low_poly_forest.glb --transform 
Files: low_poly_forest.glb [2.29MB] > /Users/dhruvyadav/3dGame/public/models/low_poly_forest-transformed.glb [78.9KB] (97%)
Author: NorTEEN_X (https://sketchfab.com/norten77077)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-forest-da6eecdaebe54d9ea06d7b52408809e9
Title: Low Poly Forest
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from "@react-three/rapier"


export function Low_poly_forest(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_forest-transformed.glb')
  return (
    <RigidBody type="fixed" colliders="trimesh"  scale={[0.4,0.4,0.4]}>
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001}  position={[0, -5.101, 36.979]} scale={169.274} />
        <instancedMesh args={[nodes.Object_1.geometry, materials.PaletteMaterial001, 52]} instanceMatrix={nodes.Object_1.instanceMatrix} /> 
        <instancedMesh args={[nodes.Object_2.geometry, materials.PaletteMaterial001, 49]} instanceMatrix={nodes.Object_2.instanceMatrix} />
        <instancedMesh args={[nodes.Object_3.geometry, materials.PaletteMaterial001, 50]} instanceMatrix={nodes.Object_3.instanceMatrix} /> 
        <instancedMesh args={[nodes.Object_4_1.geometry, materials.PaletteMaterial001, 45]} instanceMatrix={nodes.Object_4_1.instanceMatrix} />
        <instancedMesh args={[nodes.Object_219.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Object_219.instanceMatrix} />
        <instancedMesh args={[nodes.Object_223.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Object_223.instanceMatrix} />
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/low_poly_forest-transformed.glb')
