/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 low_poly_city.glb -T --instance --simplify --weld 0.0001 --ratio 0.5 
Files: low_poly_city.glb [24.31MB] > /Users/dhruvyadav/Desktop/1.WEBDEV/3dportfolio/public/low_poly_city-transformed.glb [817.79KB] (97%)
Author: Alessandro.Diamanti (https://sketchfab.com/diamanti.alessandro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-city-41697300a4c643d089784b8688b2ed2c
Title: Low Poly City
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"

export function Model(props) {
  const { nodes, materials } = useGLTF("/low_poly_city-transformed.glb")
  return (
    <RigidBody type="fixed" colliders="trimesh" position={[0,0,0]}>
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.Casa002_Colore_0.geometry}
          material={materials.Colore}
          position={[7.177, 2.163, 8.46]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={1.442}
        />
        <mesh
          geometry={nodes.Casa002_Vetro_0.geometry}
          material={materials.Vetro}
          position={[7.177, 2.163, 8.46]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={1.442}
        />
        <mesh
          geometry={nodes.BlackBoard_Texture_Varie_0.geometry}
          material={materials.Texture_Varie}
          position={[4.463, 0.702, 13.476]}
          rotation={[-Math.PI / 2, 0, -0.84]}
        />
        <mesh
          geometry={nodes.Plane001_Texture_Strada_0.geometry}
          material={materials.Texture_Strada}
          position={[-33.847, 0, 0.77]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh geometry={nodes.Tubes__0.geometry} material={materials.Tubes__0} position={[12.656, 4.544, -19.733]} rotation={[0, 0, -1.294]} />
        <mesh
          geometry={nodes.Plane046_ContornoEdifici_0.geometry}
          material={materials.ContornoEdifici}
          position={[66.153, -0.251, -79.23]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh geometry={nodes.Plane011_Marcapiede_0.geometry} material={materials.Marcapiede} position={[35.08, 0, -28.157]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh
          geometry={nodes.Ruote_Dx_Material_0.geometry}
          material={materials.Material}
          position={[-30.254, -0.328, -59.33]}
          rotation={[Math.PI / 2, 1.571, 0]}
          scale={0.777}
        />
        <instancedMesh args={[nodes.Vasi_e_Cespugli_Colore_0.geometry, materials.Colore, 5]} instanceMatrix={nodes.Vasi_e_Cespugli_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Plane002_Colore_0.geometry, materials.Colore, 7]} instanceMatrix={nodes.Plane002_Colore_0.instanceMatrix} />
        <instancedMesh
          args={[nodes.Plane002_Texture_Strada_0.geometry, materials.Texture_Strada, 11]}
          instanceMatrix={nodes.Plane002_Texture_Strada_0.instanceMatrix}
        />
        <instancedMesh args={[nodes.Plane004_Colore_0.geometry, materials.Colore, 9]} instanceMatrix={nodes.Plane004_Colore_0.instanceMatrix} />
        <instancedMesh
          args={[nodes.Plane019_Texture_Strada_0.geometry, materials.Texture_Strada, 19]}
          instanceMatrix={nodes.Plane019_Texture_Strada_0.instanceMatrix}
        />
        <instancedMesh args={[nodes.Plane025_Colore_0.geometry, materials.Colore, 8]} instanceMatrix={nodes.Plane025_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Plane049_Colore_0.geometry, materials.Colore, 6]} instanceMatrix={nodes.Plane049_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Balcone_Colore_0.geometry, materials.Colore, 10]} instanceMatrix={nodes.Balcone_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Tetto_Colore_0.geometry, materials.Colore, 5]} instanceMatrix={nodes.Tetto_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Persiane_Colore_0.geometry, materials.Colore, 10]} instanceMatrix={nodes.Persiane_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Persiane002_Colore_0.geometry, materials.Colore, 5]} instanceMatrix={nodes.Persiane002_Colore_0.instanceMatrix} />
        <instancedMesh
          args={[nodes["Vase(Simple)002_Colore_0"].geometry, materials.Colore, 13]}
          instanceMatrix={nodes["Vase(Simple)002_Colore_0"].instanceMatrix}
        />
        <instancedMesh args={[nodes.Dumpster001_Colore_0.geometry, materials.Colore, 8]} instanceMatrix={nodes.Dumpster001_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Base_Tree002_Colore_0.geometry, materials.Colore, 6]} instanceMatrix={nodes.Base_Tree002_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.tire_Colore_0.geometry, materials.Colore, 63]} instanceMatrix={nodes.tire_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Camion001_Vetro_0.geometry, materials.Vetro, 7]} instanceMatrix={nodes.Camion001_Vetro_0.instanceMatrix} />
        <instancedMesh args={[nodes.Ruote_Camion001_Colore_0.geometry, materials.Colore, 7]} instanceMatrix={nodes.Ruote_Camion001_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.OilBarrel_Colore_0.geometry, materials.Colore, 12]} instanceMatrix={nodes.OilBarrel_Colore_0.instanceMatrix} />
        <instancedMesh
          args={[nodes.Plane056_ContornoEdifici_0.geometry, materials.ContornoEdifici, 11]}
          instanceMatrix={nodes.Plane056_ContornoEdifici_0.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Plane054_ContornoEdifici_0.geometry, materials.ContornoEdifici, 6]}
          instanceMatrix={nodes.Plane054_ContornoEdifici_0.instanceMatrix}
        />
        <instancedMesh args={[nodes.Plane087_Marcapiede_0.geometry, materials.Marcapiede, 42]} instanceMatrix={nodes.Plane087_Marcapiede_0.instanceMatrix} />
        <instancedMesh args={[nodes.Plane159_Colore_0.geometry, materials.Colore, 7]} instanceMatrix={nodes.Plane159_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Bench001_Colore_0.geometry, materials.Colore, 23]} instanceMatrix={nodes.Bench001_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Pole_Colore_0.geometry, materials.Colore, 33]} instanceMatrix={nodes.Pole_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.BusStopSign001_Colore_0.geometry, materials.Colore, 5]} instanceMatrix={nodes.BusStopSign001_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Bin001_Colore_0.geometry, materials.Colore, 5]} instanceMatrix={nodes.Bin001_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Stop_Colore_0.geometry, materials.Colore, 5]} instanceMatrix={nodes.Stop_Colore_0.instanceMatrix} />
        <instancedMesh args={[nodes.Stop_Texture_Strada_0.geometry, materials.Texture_Strada, 5]} instanceMatrix={nodes.Stop_Texture_Strada_0.instanceMatrix} />
      </group>
    </RigidBody>
  )
}

useGLTF.preload("/low_poly_city-transformed.glb")
