/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useEffect } from 'react'

export function Scene(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions);

  //play the actions
  useEffect(() => {
    actions["Take 001"].play()
  }
    , [actions])


  return (
    <group ref={group} {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh" >
        <group name="Scene">
          <group name="RootNode" position={[0, -1.5, 0]}>
            <group name="pCylinder69" position={[0.716, 2.645, 4.208]} scale={[0.105, 0.909, 0.105]}>
              <mesh name="pCylinder69_Madera_2_0" geometry={nodes.pCylinder69_Madera_2_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
          <mesh name="pCube1_Madera_3_0" geometry={nodes.pCube1_Madera_3_0.geometry} material={materials.PaletteMaterial001} position={[0.192, 5.285, 28.913]} scale={[7.042, 14.185, 2.645]} />
          <mesh name="pPlane2_Agua_0" geometry={nodes.pPlane2_Agua_0.geometry} material={materials.PaletteMaterial002} position={[0, 13.02, 29.071]} scale={5.395} />
          <mesh name="pPlatonic33_Vapor_0" geometry={nodes.pPlatonic33_Vapor_0.geometry} material={materials.PaletteMaterial003} position={[-2.066, 0.799, 25.62]} />
          <mesh name="pCylinder71_Fuego_0" geometry={nodes.pCylinder71_Fuego_0.geometry} material={materials.PaletteMaterial004} position={[0.716, 2.312, 4.194]} scale={[0.053, 0.067, 0.076]} />
          <mesh name="pCube2_Foundation_0" geometry={nodes.pCube2_Foundation_0.geometry} material={materials.Foundation} position={[-13.043, 1.981, 3.14]} scale={[0.814, 0.58, 0.937]} />
          <mesh name="pCube2_Walls_0" geometry={nodes.pCube2_Walls_0.geometry} material={materials.Walls} position={[-13.043, 1.981, 3.14]} scale={[0.814, 0.58, 0.937]} />
          <mesh name="pCube3_Window_B_0" geometry={nodes.pCube3_Window_B_0.geometry} material={materials.Window_B} position={[-9.224, 6.104, -0.042]} rotation={[0, 0, -0.069]} scale={[0.462, 1.085, 0.787]} />
          <mesh name="pCube4_Flower_Box_1_0" geometry={nodes.pCube4_Flower_Box_1_0.geometry} material={materials.Flower_Box_1} position={[-8.695, 4.658, -0.042]} rotation={[-Math.PI / 2, -1.502, 0]} scale={[0.369, 0.83, 0.442]} />
          <mesh name="pCube7_Window_N_0" geometry={nodes.pCube7_Window_N_0.geometry} material={materials.Window_N} position={[-9.224, 6.104, -2.112]} rotation={[0, 0, -0.069]} scale={[0.462, 1.085, 0.787]} />
          <mesh name="pCube8_Flower_Box_2_0" geometry={nodes.pCube8_Flower_Box_2_0.geometry} material={materials.Flower_Box_2} position={[-8.695, 4.658, -2.112]} rotation={[-Math.PI / 2, -1.502, 0]} scale={[0.369, 0.83, 0.442]} />
          <mesh name="pCube18_Door_texture_0" geometry={nodes.pCube18_Door_texture_0.geometry} material={materials.Door_texture} position={[-12.871, 0, 0]} scale={0.787} />
          <mesh name="pCube20_Stair_0" geometry={nodes.pCube20_Stair_0.geometry} material={materials.Stair} position={[-8.948, 0.608, -2.128]} scale={[0.373, 0.112, 0.491]} />
          <mesh name="pCube27_Window_onning_0" geometry={nodes.pCube27_Window_onning_0.geometry} material={materials.Window_onning} position={[-9.245, 1.201, -0.046]} scale={[0.692, 0.787, 0.626]} />
          <mesh name="pCube28_Trim_0" geometry={nodes.pCube28_Trim_0.geometry} material={materials.Trim} position={[-13.059, 4.254, 3.335]} scale={[1.298, 0.04, 1.05]} />
          <mesh name="pCube28_Roof1_0" geometry={nodes.pCube28_Roof1_0.geometry} material={materials.Roof1} position={[-13.059, 4.254, 3.335]} scale={[1.298, 0.04, 1.05]} />
          <mesh name="pCube33_Trim_detail_0" geometry={nodes.pCube33_Trim_detail_0.geometry} material={materials.Trim_detail} position={[-16.25, 11.242, 2.343]} rotation={[0.052, 0, 0]} scale={[0.151, 0.186, 0.251]} />
          <mesh name="pPlane1_lambert1_0" geometry={nodes.pPlane1_lambert1_0.geometry} material={materials.lambert1} position={[-10.28, 0.308, 2.566]} rotation={[0, 0, -1.708]} scale={[0.596, 0.596, 0.787]} />
          <mesh name="pCube43_Air_condi_0" geometry={nodes.pCube43_Air_condi_0.geometry} material={materials.Air_condi} position={[-15.314, 12.089, -4.887]} scale={0.534} />
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/scene.glb')
