/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tree.glb 
Author: Sahir Virmani (https://sketchfab.com/sahirvirmani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/giant-low-poly-tree-acfd2b7f80894848b56c2ac8e7e59572
Title: Giant Low Poly Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/tree.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.407}>
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.tree_wood} scale={[1, 1, 6.687]} />
        <mesh geometry={nodes.Icosphere_0.geometry} material={materials['leaf_green.003']} position={[0.031, 1.99, 20.565]} scale={2.444} />
        <mesh geometry={nodes.Icosphere001_0.geometry} material={materials['leaf_green.004']} position={[-12.058, 11.582, 18.505]} scale={2.444} />
        <mesh geometry={nodes.Icosphere002_0.geometry} material={materials['leaf_green.001']} position={[-12.831, -4.373, 18.68]} scale={2.444} />
        <mesh geometry={nodes.Icosphere003_0.geometry} material={materials.leaf_green} position={[13.319, 3.809, 20.565]} scale={2.444} />
        <mesh geometry={nodes.Icosphere004_0.geometry} material={materials['leaf_green.002']} position={[5.025, -8, 16.588]} scale={2.444} />
        <mesh geometry={nodes.Icosphere005_0.geometry} material={materials['leaf_green.005']} position={[1.938, 12.597, 17.613]} scale={2.444} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
