/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 city.glb --T 
Files: city.glb [8.21MB] > /Users/dhruvyadav/3dGame/public/models/Town2/city-transformed.glb [382.38KB] (95%)
Author: Invictus.Art.00 (https://sketchfab.com/Invictus.Art.00)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/city-deb4dc75e62346c19c117bf61334eeb5
Title: City
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/city-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.plane_materiale_base_0.geometry} material={materials.materiale_base} position={[0, 443.732, 1323.154]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.base_casa002_vetro_0.geometry} material={materials.vetro} position={[3336.994, 483.9, -349.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pizzeria_mattoni_0.geometry} material={materials.mattoni} position={[-2766.014, 482.006, 3158.569]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Plane002_onlytexture003_0.geometry} material={materials['onlytexture.003']} position={[1270.251, 484.384, -1192.933]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
      <mesh geometry={nodes.cartello_P006_cartelli_0.geometry} material={materials.cartelli} position={[-1422.229, 482.006, -1292.275]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
      <instancedMesh args={[nodes.seemaforo011_materiale_base_0.geometry, materials.materiale_base, 6]} instanceMatrix={nodes.seemaforo011_materiale_base_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/city-transformed.glb')
