/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dog1.glb --transform 
Files: dog1.glb [2.93MB] > /Users/dhruvyadav/3dGame/public/models/Town1/dog1-transformed.glb [771.49KB] (74%)
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dog-puppy-72331763040e4314b154f84348fe0957
Title: Dog Puppy
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dog1(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Town1/dog1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.material} skeleton={nodes.Object_7.skeleton} scale={1.75} />
      </group>
    </group>
  )
}

useGLTF.preload('/dog1-transformed.glb')
