/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dog2.glb --transform 
Files: dog2.glb [787.01KB] > /Users/dhruvyadav/3dGame/public/models/Town1/dog2-transformed.glb [119.35KB] (85%)
Author: Artsiom Savelyeu (https://sketchfab.com/artsiom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-shar-pei-animated-dog-ed151fd59a894b3290d9eee3f716f0bf
Title: Free Shar Pei Animated Dog
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dog2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Town1/dog2-transformed.glb')
  const { actions } = useAnimations(animations, group)

  console.log(actions);

  useEffect(() => {
    actions['standing_idle']?.play();
  }
    , [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.lambert1} skeleton={nodes.Object_7.skeleton} scale={0.141} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.lambert1} skeleton={nodes.Object_9.skeleton} scale={0.141} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.lambert1} skeleton={nodes.Object_11.skeleton} scale={0.141} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.lambert1} skeleton={nodes.Object_13.skeleton} scale={0.141} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.lambert1} skeleton={nodes.Object_15.skeleton} scale={0.141} />
      </group>
    </group>
  )
}

useGLTF.preload('/dog2-transformed.glb')
